website/bands/urls.py
from django.urls import path
from . import views
#from accounts import views as accounts_views

app_name = 'bands'
urlpatterns = [
    # post views
    path('', views.list_bands, name='list_bands'),
    path('country', views.list_countries, name='list_countries'),
    path('country/<int:id>/', views.detail_country, name='detail_country'),
    path('country_bands/<int:id>/', views.list_country_bands, name='list_country_bands'),
    path('genre', views.list_genres, name='list_genres'),
    path('genre/<int:id>/', views.detail_genre, name='detail_genre'),
    path('genre/ajout', views.ajout_genre, name='ajout_genre'),
    path('genre/supp/<int:id>', views.supprimer_genre, name='supprimer_genre'),
    path('genre/modif/<int:id>', views.modifier_genre, name='modifier_genre'),
    path('genre_bands/<int:id>/', views.list_genre_bands, name='list_genre_bands'),
    path('band', views.list_bands, name='list_bands'),
    path('band/<int:id>/<str:redirect_to>', views.detail_band, name='detail_band'),
    path('band/ajout', views.ajout_band, name='ajout_band'),
    path('band/supp/<int:id>', views.supprimer_band, name='supprimer_band'),
    path('band/modif/<int:id>', views.modifier_band, name='modifier_band'),
    path('band/aimer/<int:id>', views.aimer_band, name='aimer_band'),
    path('band/a_ecouter/<int:id>', views.a_ecouter_band, name='a_ecouter_band'),
    path('band/inscrire_ecoute/<int:id>/<str:redirect_to>', views.inscrire_ecoute_band, name='inscrire_ecoute_band'),
    path('band/ne_pas_aimer/<int:id>', views.ne_pas_aimer_band, name='ne_pas_aimer_band'),
    path('bandlink/ajout/<int:band_id>/', views.ajout_bandlink, name='ajout_bandlink'),
    path('bandlink/supp/<int:band_id>/<int:id>', views.supprimer_bandlink, name='supprimer_bandlink'),
    path('band/choisir_pays/<int:id>', views.band_choisir_pays, name='band_choisir_pays'),
    path('band/ajout_pays/<int:band_id>/<int:id>', views.band_ajouter_pays, name='band_ajouter_pays'),
    path('band/enlever_pays/<int:band_id>/<int:id>', views.band_enlever_pays, name='band_enlever_pays'),
    path('band/choisir_genre/<int:id>', views.band_choisir_genre, name='band_choisir_genre'),
    path('band/ajout_genre/<int:band_id>/<int:id>', views.band_ajouter_genre, name='band_ajouter_genre'),
    path('band/enlever_genre/<int:band_id>/<int:id>', views.band_enlever_genre, name='band_enlever_genre'),
    path('band/liste_a_ecouter', views.liste_a_ecouter, name='liste_a_ecouter'),
    path('band/liste_ecoutes', views.liste_ecoutes, name='liste_ecoutes'),
    path('band/mes_bands', views.list_my_bands, name='list_my_bands'),
]

website/bands/templates/bands/genre/ajout.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Ajouter un Nouveau Genre</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                            <a href="{% url 'bands:list_genres' %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

website/bands/templates/bands/genre/detail.html
{% extends "base.html" %}
{% block title %}Genre - Vue détaillée{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Vue détaillée: {{ genre.genre_name }}</h1>
        </div>
        <p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Attribut</th>
                        <th scope="col">Valeur</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Nom</td>
                        <td>{{ genre.genre_name }}</td>
                    </tr>
                    <tr>
                        <td>Description</td>
                        {% if genre.genre_desc %}
                            <td>{{ genre.genre_desc }}</td>
                        {% else %}
                            <td>&nbsp;</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Ajouté par</td>
                        <td>{{ genre.aud_crt_user.username }}</td>
                    </tr>
                    <tr>
                        <td>Ajouté le</td>
                        <td>{{ genre.aud_crt_ts }}</td>
                    </tr>
                    <tr>
                        <td>Mis à jour par</td>
                        {% if genre.aud_upd_user %}
                            <td>{{ genre.aud_upd_user.username }}</td>
                        {% else %}
                            <td>Pas de mise à jour</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Mis à jour le</td>
                        {% if genre.aud_upd_user %}
                            <td>{{ genre.aud_upd_ts }}</td>
                        {% else %}
                            <td>Pas de mise à jour</td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        </p>
        <p>
            <a href="{% url 'bands:list_genres' %}" class="btn btn-primary">Retour à la liste</a>
        </p>
    </div>
{% endblock %}

website/bands/templates/bands/genre/list.html
{% extends "base.html" %}
{% block title %}Liste des Genres{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Liste des Genres</h1>
    </div>
    <p>
        {% if maj_permises %}
            <a href="{% url 'bands:ajout_genre' %}" class="btn btn-primary">Ajouter un Genre</a>
        {% endif %}
        {% include "pagination.html" with page=genres %}
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Ajouté par</th>
                    {% if maj_permises %}
                        <th scope="col">Actions</th>
                    {% endif %}
                    <th scope="col">Nb de Bands</th>
                </tr>
            </thead>
            <tbody>
                {% for g in genres %}
                    <tr>
                        <td>
                            <a href="{% url 'bands:detail_genre' g.id %}">{{ g.genre_name }}</a>
                        </td>
                        <td>{{ g.aud_crt_user.username }} le {{ g.aud_crt_ts }}</td>
                        {% if maj_permises %}
                            <td class="text-center">
                                <a href="{% url 'bands:modifier_genre' g.id %}"
                                class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier">
                                <span class="bi-pencil"></span>
                                </a>
                                <a href="{% url 'bands:supprimer_genre' g.id %}"
                                class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Supprimer">
                                <span class="bi-trash"></span>
                                </a>
                            </td>
                        {% endif %}
                        <td>
                            {% if g.genre_played_by_bands.count == 0 %}
                                0
                            {% else %}
                                <a href="{% url 'bands:list_genre_bands' g.id %}">{{ g.genre_played_by_bands.count}}</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "pagination.html" with page=genres %}
        {% if maj_permises %}
            <a href="{% url 'bands:ajout_genre' %}" class="btn btn-primary">Ajouter un Genre</a>
        {% endif %}
    </p>
</div>
{% endblock %}

website/bands/templates/bands/genre/list_bands.html
{% extends "base.html" %}
{% block title %}Liste des Bands du Genre: {{ genre.genre_name }} {% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Liste des Bands du Genre: {{ genre.genre_name }}</h1>
    </div>
    <p>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                </tr>
            </thead>
            <tbody>
                {% for b in genre.genre_played_by_bands.all %}
                    <tr>
                        <td><a href="{% url 'bands:detail_band' b.id 'genres' %}">{{ b.band_name }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
    <p>
        <a href="{% url 'bands:list_genres' %}" class="btn btn-primary">Liste des Genres</a>
    </p>
</div>
{% endblock %}

website/bands/templates/bands/genre/modif.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h5 class="card-title">Modifier un Genre</h5>
                {% if error %}
                    <div class="alert alert-danger mt-3" role="alert">
                        {{ error }}
                    </div>
                {% endif %}
                <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Modifier</button>
                        <a href="{% url 'bands:list_genres' %}" class="btn btn-primary">Annuler</a>
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

website/bands/templates/bands/genre/supp.html
{% extends "base.html" %}
{% block title %}Supprimer un Genre{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Supprimer le genre {{ genre.genre_name }}</h1>
        </div>
        <div class="module">
            <form action="" method="post">
                {% csrf_token %}
                <p>Es-tu sûr de vouloir supprimer ce genre?</p>
                <p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Attribut</th>
                                <th scope="col">Valeur</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Nom</td>
                                <td>{{ genre.genre_name }}</td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                {% if genre.genre_desc %}
                                    <td>{{ genre.genre_desc }}</td>
                                {% else %}
                                    <td>&nbsp;</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>Ajouté par</td>
                                <td>{{ genre.aud_crt_user.username }}</td>
                            </tr>
                            <tr>
                                <td>Ajouté le</td>
                                <td>{{ genre.aud_crt_ts }}</td>
                            </tr>
                            <tr>
                                <td>Mis à jour par</td>
                                {% if genre.aud_upd_user %}
                                    <td>{{ genre.aud_crt_user.username }}</td>
                                {% else %}
                                    <td>Pas de mise à jour</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>Mis à jour le</td>
                                {% if genre.aud_upd_user %}
                                    <td>{{ genre.aud_crt_ts }}</td>
                                {% else %}
                                    <td>Pas de mise à jour</td>
                                {% endif %}
                            </tr>
                        </tbody>
                    </table>
                </p>
                <p>
                    <button type="submit" class="btn btn-primary">Oui</button>
                    <a href="{% url 'bands:list_genres' %}" class="btn btn-primary">Non</a>
                </p>
            </form>
        </div>
    </div>
{% endblock %}