website/bands/urls.py
from django.urls import path
from . import views
#from accounts import views as accounts_views

app_name = 'bands'
urlpatterns = [
    # post views
    path('', views.list_bands, name='list_bands'),
    path('country', views.list_countries, name='list_countries'),
    path('country/<int:id>/', views.detail_country, name='detail_country'),
    path('country_bands/<int:id>/', views.list_country_bands, name='list_country_bands'),
    path('genre', views.list_genres, name='list_genres'),
    path('genre/<int:id>/', views.detail_genre, name='detail_genre'),
    path('genre/ajout', views.ajout_genre, name='ajout_genre'),
    path('genre/supp/<int:id>', views.supprimer_genre, name='supprimer_genre'),
    path('genre/modif/<int:id>', views.modifier_genre, name='modifier_genre'),
    path('genre_bands/<int:id>/', views.list_genre_bands, name='list_genre_bands'),
    path('band', views.list_bands, name='list_bands'),
    path('band/<int:id>/<str:redirect_to>', views.detail_band, name='detail_band'),
    path('band/ajout', views.ajout_band, name='ajout_band'),
    path('band/supp/<int:id>', views.supprimer_band, name='supprimer_band'),
    path('band/modif/<int:id>', views.modifier_band, name='modifier_band'),
    path('band/aimer/<int:id>', views.aimer_band, name='aimer_band'),
    path('band/a_ecouter/<int:id>', views.a_ecouter_band, name='a_ecouter_band'),
    path('band/inscrire_ecoute/<int:id>/<str:redirect_to>', views.inscrire_ecoute_band, name='inscrire_ecoute_band'),
    path('band/ne_pas_aimer/<int:id>', views.ne_pas_aimer_band, name='ne_pas_aimer_band'),
    path('bandlink/ajout/<int:band_id>/', views.ajout_bandlink, name='ajout_bandlink'),
    path('bandlink/supp/<int:band_id>/<int:id>', views.supprimer_bandlink, name='supprimer_bandlink'),
    path('band/choisir_pays/<int:id>', views.band_choisir_pays, name='band_choisir_pays'),
    path('band/ajout_pays/<int:band_id>/<int:id>', views.band_ajouter_pays, name='band_ajouter_pays'),
    path('band/enlever_pays/<int:band_id>/<int:id>', views.band_enlever_pays, name='band_enlever_pays'),
    path('band/choisir_genre/<int:id>', views.band_choisir_genre, name='band_choisir_genre'),
    path('band/ajout_genre/<int:band_id>/<int:id>', views.band_ajouter_genre, name='band_ajouter_genre'),
    path('band/enlever_genre/<int:band_id>/<int:id>', views.band_enlever_genre, name='band_enlever_genre'),
    path('band/liste_a_ecouter', views.liste_a_ecouter, name='liste_a_ecouter'),
    path('band/liste_ecoutes', views.liste_ecoutes, name='liste_ecoutes'),
    path('band/mes_bands', views.list_my_bands, name='list_my_bands'),
]

website/bands/templates/bands/band/a_ecouter.html
{% extends "base.html" %}
{% block title %}Liste de bands à écouter{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Bands à écouter</h1>
    </div>
    <p>
        {% if bands %}
            {% include "pagination.html" with page=bands %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th scope="col">Nom</th>
                        <th scope="col">Ajouté le</th>
                        <th scope="col">Liens</th>
                        <th scope="col">Marquer</th>
                    </tr>
                </thead>
                <tbody>
                    {% for b in bands %}
                        <tr>
                            <td>
                                <a href="{% url 'bands:detail_band' b.band.id 'a_ecouter' %}">{{ b.band.band_name }}</a>
                            </td>
                            <td>{{ b.added_ts }}</td>
                            <td>
                                {% for l in b.band.link_for_a_band.all %}
                                    <a href="{{ l.link_url }}" target="_blank" rel="noopener noreferrer">{{ l.link_name }}</a>
                                {% endfor %}
                            </td>
                            <td><a href="{% url 'bands:inscrire_ecoute_band' b.band.id 'a_ecouter' %}"
                                class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="J'ai écouté">
                                <span class="bi-check"></span></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "pagination.html" with page=bands %}
        {% else %}
            Tu n'as rien à écouter.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Tous les bands</a>
    </p>
</div>
{% endblock %}

website/bands/templates/bands/band/ajout.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Ajouter un Nouveau Band</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                            <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

website/bands/templates/bands/band/choisir_genre.html
{% extends "base.html" %}
{% block title %}Band - Ajouter un genre{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Genres disponibles pour: {{ band.band_name }}</h1>
        </div>
        <p>
            <a href="{% url 'bands:modifier_band' band.id %}" class="btn btn-primary">Retour</a>
        </p>
        <ul class="list-group">
            {% if genres %}
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Appellation</th>
                            <th class="text-center" scope="col">Choisir</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for g in genres %}
                            {% if g.id not in curr_genres %}
                                <tr>
                                    <td>{{ g.genre_name }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'bands:band_ajouter_genre' band.id g.id %}"
                                        class="btn btn-success btn-sm" data-title="Ajouter">
                                        <span class="bi-plus-circle"></span>
                                        </a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Pas de genres.
            {% endif %}
        </ul>
        </p>
        <p>
            <a href="{% url 'bands:modifier_band' band.id %}" class="btn btn-primary">Retour</a>
        </p>
    </div>
{% endblock %}

website/bands/templates/bands/band/choisir_pays.html
{% extends "base.html" %}
{% block title %}Band - Ajouter un pays{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Pays disponibles pour: {{ band.band_name }}</h1>
        </div>
        <p>
            <a href="{% url 'bands:modifier_band' band.id %}" class="btn btn-primary">Retour</a>
        </p>
        <ul class="list-group">
            {% if countries %}
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Alpha 2</th>
                            <th scope="col">Alpha 3</th>
                            <th class="text-center" scope="col">Choisir</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in countries %}
                            {% if c.id not in curr_countries %}
                                <tr>
                                    <td>{{ c.country_name_fr }}</td>
                                    <td>{{ c.country_alpha2 }}</td>
                                    <td>{{ c.country_alpha3 }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'bands:band_ajouter_pays' band.id c.id %}"
                                        class="btn btn-success btn-sm" data-title="Retirer">
                                        <span class="bi-plus-circle"></span>
                                        </a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Pas de pays.
            {% endif %}
        </ul>
        </p>
        <p>
            <a href="{% url 'bands:modifier_band' band.id %}" class="btn btn-primary">Retour</a>
        </p>
    </div>
{% endblock %}

website/bands/templates/bands/band/dernieres_ecoutes.html
{% extends "base.html" %}
{% block title %}Liste des dernières écoutes{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Dernières écoutes</h1>
    </div>
    <p>
        {% if bands %}
            {% include "pagination.html" with page=bands %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th scope="col">Nom</th>
                        <th scope="col">Écoutté le</th>
                        <th scope="col">Liens</th>
                        <th scope="col">Réécouter</th>
                    </tr>
                </thead>
                <tbody>
                    {% for b in bands %}
                        <tr>
                            <td>
                                <a href="{% url 'bands:detail_band' b.band.id 'liste_ecoutes' %}">{{ b.band.band_name }}</a>
                            </td>
                            <td>{{ b.added_ts }}</td>
                            <td>
                                {% for l in b.band.link_for_a_band.all %}
                                    <a href="{{ l.link_url }}" target="_blank" rel="noopener noreferrer">{{ l.link_name }}</a>
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'bands:a_ecouter_band' b.id %}"
                                    class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="À réécouter">
                                    <span class="bi-music-note-list"></span>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "pagination.html" with page=bands %}
        {% else %}
            Tu n'as rien écouté.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Tous les bands</a>
    </p>
</div>
{% endblock %}

website/bands/templates/bands/band/detail.html
{% extends "base.html" %}
{% block title %}Band - Vue détaillée{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Vue détaillée: {{ band.band_name }}</h1>
        </div>
        <p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Attribut</th>
                        <th scope="col">Valeur</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Nom</td>
                        <td>{{ band.band_name }}</td>
                    </tr>
                    <tr>
                        <td>Description</td>
                        {% if band.band_desc %}
                            <td>{{ band.band_desc }}</td>
                        {% else %}
                            <td>&nbsp;</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Ajouté par</td>
                        <td>{{ band.aud_crt_user.username }}</td>
                    </tr>
                    <tr>
                        <td>Ajouté le</td>
                        <td>{{ band.aud_crt_ts }}</td>
                    </tr>
                    <tr>
                        <td>Mis à jour par</td>
                        {% if band.aud_upd_user %}
                            <td>{{ band.aud_upd_user.username }}</td>
                        {% else %}
                            <td>Pas de mise à jour</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Mis à jour le</td>
                        {% if band.aud_upd_user %}
                            <td>{{ band.aud_upd_ts }}</td>
                        {% else %}
                            <td>Pas de mise à jour</td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        <hr />
        <h3>Liens</h3>
        <ul class="list-group">
            {% if links %}
                {% for l in links %}
                <li class="list-group-item pb-3 pt-3">
                    <h5 class="card-title">
                    {{ l.link_name }}
                    </h5>
                    <p class="card-text">
                        <a href="{{ l.link_url }}" target="_blank" rel="noopener noreferrer">{{ l.link_url }}</a>
                    </p>
                </li>
                {% endfor %}
            {% else %}
                Pas de liens.
            {% endif %}
        </ul>
        <hr />
        <h3>Genres</h3>
        <ul class="list-group">
            {% if genres %}
                {% for g in genres %}
                <li class="list-group-item pb-3 pt-3">
                    <h5 class="card-title">
                    {{ g.genre_name }}
                    </h5>
                </li>
                {% endfor %}
            {% else %}
                Pas de genre défini.
            {% endif %}
        </ul>
        <hr />
        <h3>Pays</h3>
        <ul class="list-group">
            {% if countries %}
                {% for c in countries %}
                <li class="list-group-item pb-3 pt-3">
                    <h5 class="card-title">
                    {{ c.country_name_fr }}
                    </h5>
                </li>
                {% endfor %}
            {% else %}
                Pas de pays défini.
            {% endif %}
        </ul>
        </p>
        <p>
            {% if redirect_to == "list_bands" %}
                <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Retour à la liste</a>
            {% elif redirect_to == "mes_bands" %}
                <a href="{% url 'bands:list_my_bands' %}" class="btn btn-primary">Retour à la liste</a>
            {% elif redirect_to == "a_ecouter" %}
                <a href="{% url 'bands:liste_a_ecouter' %}" class="btn btn-primary">Retour à la liste</a>
            {% elif redirect_to == "countries" %}
                <a href="{% url 'bands:list_countries' %}" class="btn btn-primary">Retour à la liste</a>
            {% elif redirect_to == "genres" %}
                <a href="{% url 'bands:list_genres' %}" class="btn btn-primary">Retour à la liste</a>
            {% else %}
                <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Retour à la liste</a>
            {% endif %}
        </p>
    </div>
{% endblock %}

website/bands/templates/bands/band/list.html
{% extends "base.html" %}
{% block title %}Liste des Bands{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Liste des Bands</h1>
    </div>
    <p>
        {% if maj_permises %}
            <a href="{% url 'bands:ajout_band' %}" class="btn btn-primary">Ajouter un Band</a>
        {% endif %}
        {% include "pagination.html" with page=bands %}
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Ajouté par</th>
                    {% if maj_permises %}<th class="text-center" scope="col">Actions</th>{% endif %}
                </tr>
            </thead>
            <tbody>
                {% for b in bands %}
                    <tr>
                        <td>
                            <a href="{% url 'bands:detail_band' b.id 'list_bands' %}">{{ b.band_name }}</a>
                        </td>
                        <td>{{ b.aud_crt_user.username }} le {{ b.aud_crt_ts }}</td>
                        {% if maj_permises %}
                            <td class="text-center">
                                <a href="{% url 'bands:modifier_band' b.id %}"
                                class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Modifier">
                                <span class="bi-pencil"></span>
                                </a>
                                <a href="{% url 'bands:supprimer_band' b.id %}"
                                class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Supprimer">
                                <span class="bi-trash"></span>
                                </a>
                                {% if b.is_fan %}
                                    <a href="{% url 'bands:ne_pas_aimer_band' b.id %}"
                                    class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Ne plus aimer">
                                    <span class="bi-heartbreak-fill"></span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'bands:aimer_band' b.id %}"
                                    class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Aimer">
                                    <span class="bi-heart-fill"></span>
                                    </a>
                                {% endif %}
                                {% if b.to_listen %}
                                    <a href="{% url 'bands:inscrire_ecoute_band' b.id 'list_bands' %}"
                                    class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="J'ai écouté">
                                    <span class="bi-check"></span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'bands:a_ecouter_band' b.id %}"
                                    class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="À écouter">
                                    <span class="bi-music-note-list"></span>
                                    </a>
                                {% endif %}
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "pagination.html" with page=bands %}
        {% if maj_permises %}
            <a href="{% url 'bands:ajout_band' %}" class="btn btn-primary">Ajouter un Band</a>
        {% endif %}
    </p>
</div>
{% endblock %}

website/bands/templates/bands/band/mes_bands.html
{% extends "base.html" %}
{% block title %}Liste de mes bands{% endblock %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Liste de mes bands</h1>
    </div>
    <p>
        {% if bands %}
            {% include "pagination.html" with page=bands %}
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th scope="col">Nom</th>
                        <th scope="col">Ajouté par</th>
                        <th scope="col">Liens</th>
                    </tr>
                </thead>
                <tbody>
                    {% for b in bands %}
                        <tr>
                            <td>
                                <a href="{% url 'bands:detail_band' b.id 'mes_bands' %}">{{ b.band_name }}</a>
                            </td>
                            <td>{{ b.aud_crt_user.username }} le {{ b.aud_crt_ts }}</td>
                            <td>
                                {% for l in b.links %}
                                    <a href="{{ l.link_url }}" target="_blank" rel="noopener noreferrer">{{ l.link_name }}</a>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "pagination.html" with page=bands %}
        {% else %}
            Tu es fan d'aucun band.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Tous les bands</a>
    </p>
</div>
{% endblock %}

website/bands/templates/bands/band/modif.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h1 class="card-title">Modifier un Band</h1>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Modifier</button>
                            <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Annuler</a>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h3 class="card-title">Liens</h3>
                    <p class="card-text">
                        {% if links %}
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Nom</th>
                                        <th scope="col">Ajouté par</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for l in links %}
                                        <tr>
                                            <td>
                                                <a href="{{ l.link_url }}" target="_blank" rel="noopener noreferrer">{{ l.link_name }}</a>
                                            </td>
                                            <td>{{ l.aud_crt_user.username }} le {{ l.aud_crt_ts }}</td>
                                            <td class="text-center">
                                                <a href="#" class="btn btn-primary btn-sm" data-title="Modifier">
                                                    <span class="bi-pencil"></span>
                                                </a>
                                                <a href="{% url 'bands:supprimer_bandlink' band.id l.id%}" class="btn btn-danger btn-sm" data-title="Supprimer">
                                                    <span class="bi-trash"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                <tbody>
                            </table>
                        {% else %}
                            Pas de liens.
                        {% endif %}
                    </p>
                    <a href="{% url 'bands:ajout_bandlink' band.id %}" class="btn btn-primary">Ajouter un lien</a>
                    <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h3 class="card-title">Pays</h3>
                    <p class="card-text">
                        {% if countries %}
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Nom</th>
                                        <th scope="col">Alpha 2</th>
                                        <th scope="col">Alpha 3</th>
                                        <th class="text-center" scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for c in countries %}
                                        <tr>
                                            <td>{{ c.country_name_fr }}</td>
                                            <td>{{ c.country_alpha2 }}</td>
                                            <td>{{ c.country_alpha3 }}</td>
                                            <td class="text-center">
                                                <a href="{% url 'bands:band_enlever_pays' band.id c.id %}" class="btn btn-danger btn-sm" data-title="Retirer">
                                                    <span class="bi-dash-circle"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                <tbody>
                            </table>
                        {% else %}
                            Pas de pays.
                        {% endif %}
                    </p>
                    <a href="{% url 'bands:band_choisir_pays' band.id %}" class="btn btn-primary">Ajouter un pays</a>
                    <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h3 class="card-title">Genres</h3>
                    <p class="card-text">
                        {% if genres %}
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Appellation</th>
                                        <th class="text-center" scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for g in genres %}
                                        <tr>
                                            <td>{{ g.genre_name }}</td>
                                            <td class="text-center">
                                                <a href="{% url 'bands:band_enlever_genre' band.id g.id %}" class="btn btn-danger btn-sm" data-title="Retirer">
                                                    <span class="bi-dash-circle"></span>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                <tbody>
                            </table>
                        {% else %}
                            Pas de genres.
                        {% endif %}
                    </p>
                    <a href="{% url 'bands:band_choisir_genre' band.id %}" class="btn btn-primary">Ajouter un genre</a>
                    <a href="{% url 'bands:list_bands' %}" class="btn btn-primary">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}