website/bands/urls.py
from django.urls import path
from . import views
#from accounts import views as accounts_views

app_name = 'bands'
urlpatterns = [
    # post views
    path('', views.list_bands, name='list_bands'),
    path('country', views.list_countries, name='list_countries'),
    path('country/<int:id>/', views.detail_country, name='detail_country'),
    path('country_bands/<int:id>/', views.list_country_bands, name='list_country_bands'),
    path('genre', views.list_genres, name='list_genres'),
    path('genre/<int:id>/', views.detail_genre, name='detail_genre'),
    path('genre/ajout', views.ajout_genre, name='ajout_genre'),
    path('genre/supp/<int:id>', views.supprimer_genre, name='supprimer_genre'),
    path('genre/modif/<int:id>', views.modifier_genre, name='modifier_genre'),
    path('genre_bands/<int:id>/', views.list_genre_bands, name='list_genre_bands'),
    path('band', views.list_bands, name='list_bands'),
    path('band/<int:id>/<str:redirect_to>', views.detail_band, name='detail_band'),
    path('band/ajout', views.ajout_band, name='ajout_band'),
    path('band/supp/<int:id>', views.supprimer_band, name='supprimer_band'),
    path('band/modif/<int:id>', views.modifier_band, name='modifier_band'),
    path('band/aimer/<int:id>', views.aimer_band, name='aimer_band'),
    path('band/a_ecouter/<int:id>', views.a_ecouter_band, name='a_ecouter_band'),
    path('band/inscrire_ecoute/<int:id>/<str:redirect_to>', views.inscrire_ecoute_band, name='inscrire_ecoute_band'),
    path('band/ne_pas_aimer/<int:id>', views.ne_pas_aimer_band, name='ne_pas_aimer_band'),
    path('bandlink/ajout/<int:band_id>/', views.ajout_bandlink, name='ajout_bandlink'),
    path('bandlink/supp/<int:band_id>/<int:id>', views.supprimer_bandlink, name='supprimer_bandlink'),
    path('band/choisir_pays/<int:id>', views.band_choisir_pays, name='band_choisir_pays'),
    path('band/ajout_pays/<int:band_id>/<int:id>', views.band_ajouter_pays, name='band_ajouter_pays'),
    path('band/enlever_pays/<int:band_id>/<int:id>', views.band_enlever_pays, name='band_enlever_pays'),
    path('band/choisir_genre/<int:id>', views.band_choisir_genre, name='band_choisir_genre'),
    path('band/ajout_genre/<int:band_id>/<int:id>', views.band_ajouter_genre, name='band_ajouter_genre'),
    path('band/enlever_genre/<int:band_id>/<int:id>', views.band_enlever_genre, name='band_enlever_genre'),
    path('band/liste_a_ecouter', views.liste_a_ecouter, name='liste_a_ecouter'),
    path('band/liste_ecoutes', views.liste_ecoutes, name='liste_ecoutes'),
    path('band/mes_bands', views.list_my_bands, name='list_my_bands'),
]

website/bands/templates/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <title>{% block title %}Base{% endblock %}</title>
    </head>
    <body>
        {% block navbar %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Bands</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'bands:list_bands' %}">Accueil</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Bands</a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li><a class="dropdown-item" href="{% url 'bands:list_bands' %}">Tous les bands</a></li>
                                    {% if user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'bands:list_my_bands' %}">Mes bands</a></li>
                                        <li><a class="dropdown-item" href="{% url 'bands:liste_a_ecouter' %}">À écouter</a></li>
                                        <li><a class="dropdown-item" href="{% url 'bands:liste_ecoutes' %}">Dernières écoutes</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Références</a>
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    <li><a class="dropdown-item" href="{% url 'bands:list_countries' %}">Pays</a></li>
                                    <li><a class="dropdown-item" href="{% url 'bands:list_genres' %}">Genres</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                {% if user.is_authenticated %}
                                    {% if user.first_name %}
                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.first_name }}</a>
                                    {% else %}
                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                                    {% endif %}
                                {% else %}
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Connexion</a>
                                {% endif %}
                                <ul class="dropdown-menu dropdown-menu-dark">
                                    {% if user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Déconnexion</a></li>
                                    {% else %}
                                        <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Connexion</a></li>
                                        <li><a class="dropdown-item" href="{% url 'accounts:register_account' %}">Inscription</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endblock %}
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div class="alert alert-danger mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% elif message.tags == "warning" %}
                    <div class="alert alert-warning mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% elif message.tags == "info" %}
                    <div class="alert alert-info mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% elif message.tags == "success" %}
                    <div class="alert alert-success mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% else %}
                    <div class="alert alert-debug mt-3" role="alert">
                        {{ message|safe }}
                    </div>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <footer class="text-center text-lg-start bg-light text-muted mt-4">
            <div class="text-center p-4">Fin de la page</div>
        </footer>
    </body>
</html>

website/bands/templates/index.html
{% extends "base.html" %}
{% block title %}Pays{% endblock %}
{% block content %}
    <h1>Welcome Home</h1>
{% endblock %}

website/bands/templates/pagination.html
<div class="pagination justify-content-end">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}" class="bi-arrow-left-circle-fill"></a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} de {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}" class="bi-arrow-right-circle-fill"></a>
        {% endif %}
    </span>
</div>